### ISSUE TITLE
High resolution force

### ISSUE THREAD

**Issue by ghost** [spelufo/books-dl#1]
The images that are saved to disk are not high resolution. High resolution can be forced to modify the `&w=` get parameter to 1200 (this ensures that the images are 1200px wide).

I've tried this:

``` javascript
img.src = img.src.replace(/&w=\d+$/, "&w=1200");
```

in  the function `getPageImage()` but then the images are corrupted.

How can we force to download the high resolution of the image?

**Comment by spelufo** [comment]
I would try using the `zoomIn` method from [their API](https://developers.google.com/books/docs/viewer/reference).

**Comment by ghost** [comment]
Thanks! Using this now:

``` javascript
google.load("books", "0");
google.setOnLoadCallback(function initialize() {
  viewer = new google.books.DefaultViewer(document.getElementById('viewerCanvas'));
  viewer.load(bookid, null, alertInitialized);
})

function alertInitialized() {
  for(var i=0;i<7;i++) {
    viewer.zoomIn();
  }
  setTimeout(nextPage, 3000);
}
```
